AllCops:
  NewCops: enable
  Exclude:
    - 'coverage/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'bin/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 80

Metrics/BlockLength:
  Max: 700

Metrics/CyclomaticComplexity:
  Max: 35
Metrics/PerceivedComplexity:
  Max: 35
Metrics/AbcSize:
  Max: 50

# Disable documentation requirement for now
Style/Documentation:
  Enabled: false

# Allow longer lines for comments
Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Disable naming issues for legal/statutory references
Naming/VariableNumber:
  Enabled: false
