#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates web/text-verify/data.js from nasfaa_questions.yml.
#
# Run after editing YAML:
#
#   ruby web/text-verify/build.rb
#
# Output is a single window.NASFAA_VERIFY_DATA bundle so the page
# works under file:// without a fetcher or module loader.

require 'yaml'
require 'json'

ROOT = File.expand_path('../..', __dir__)
OUT  = File.expand_path(__dir__)

questions = YAML.safe_load_file(File.join(ROOT, 'nasfaa_questions.yml'))

bundle = {
  'start' => questions['start'],
  'nodes' => questions['nodes']
}

out_path = File.join(OUT, 'data.js')
File.open(out_path, 'w:UTF-8') do |f|
  f.write("// data.js — generated by build.rb from nasfaa_questions.yml.\n")
  f.write("// Re-run `ruby web/text-verify/build.rb` after editing YAML.\n")
  f.write("window.NASFAA_VERIFY_DATA = #{JSON.pretty_generate(bundle)};\n")
end
puts "wrote #{File.basename(out_path)} (#{File.size(out_path)} bytes)"
