#!/usr/bin/env node
//
// build.js — Regenerate rules.json, scenarios.json, and the data.js bundle
// from the canonical YAML sources at the project root.
//
// data.js is the file the static HTML loads directly (window.NASFAA_QUIZ_DATA)
// so the page works under file:// without fetch or a local HTTP server.
//
// Shells to Ruby (already a project dep) for YAML parsing — no npm install.
//
// Usage:
//   node web/quiz/build.js

'use strict';

const { execFileSync } = require('node:child_process');
const { writeFileSync, existsSync } = require('node:fs');
const path = require('node:path');

const HERE = __dirname;
const PROJECT_ROOT = path.resolve(HERE, '..', '..');
const RULES_YAML = path.join(PROJECT_ROOT, 'nasfaa_rules.yml');
const SCENARIOS_YAML = path.join(PROJECT_ROOT, 'nasfaa_scenarios.yml');
const RULES_JSON = path.join(HERE, 'rules.json');
const SCENARIOS_JSON = path.join(HERE, 'scenarios.json');
const DATA_JS = path.join(HERE, 'data.js');

function yamlToObject(yamlPath) {
  if (!existsSync(yamlPath)) {
    throw new Error(`YAML source not found: ${yamlPath}`);
  }
  const ruby = `require 'yaml'; require 'json'; ` +
               `puts JSON.pretty_generate(YAML.safe_load_file(ARGV[0]))`;
  const out = execFileSync('ruby', ['-e', ruby, yamlPath], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
  });
  return { json: out, parsed: JSON.parse(out) };
}

function gitSha() {
  try {
    return execFileSync('git', ['-C', PROJECT_ROOT, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
    }).trim() || 'dev';
  } catch {
    return 'dev';
  }
}

function build() {
  console.log('Reading', path.relative(PROJECT_ROOT, RULES_YAML));
  const rules = yamlToObject(RULES_YAML);
  writeFileSync(RULES_JSON, rules.json);
  console.log('  wrote', path.relative(PROJECT_ROOT, RULES_JSON));

  console.log('Reading', path.relative(PROJECT_ROOT, SCENARIOS_YAML));
  const scenarios = yamlToObject(SCENARIOS_YAML);
  writeFileSync(SCENARIOS_JSON, scenarios.json);
  console.log('  wrote', path.relative(PROJECT_ROOT, SCENARIOS_JSON));

  const bundle = {
    rules: rules.parsed,
    scenarios: scenarios.parsed,
    build: { sha: gitSha(), generated_at: new Date().toISOString() },
  };
  const dataJs =
    '// data.js — generated by build.js from the canonical YAML.\n' +
    '// Re-run `node web/quiz/build.js` after editing YAML.\n' +
    'window.NASFAA_QUIZ_DATA = ' + JSON.stringify(bundle, null, 2) + ';\n';
  writeFileSync(DATA_JS, dataJs);
  console.log('  wrote', path.relative(PROJECT_ROOT, DATA_JS));

  console.log('Done.');
}

try {
  build();
} catch (err) {
  console.error('build.js failed:', err.message);
  process.exit(1);
}
