#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates the JSON copies of the canonical YAML files into
# web/walkthrough/, plus a single data.js bundle that the static HTML
# pages load directly (no fetch, no module loader — works under file://).
#
# Source of truth stays in the YAML files at the repo root. Re-run after
# editing YAML:
#
#   ruby web/walkthrough/build.rb
#
# Outputs (UTF-8, LF endings, no BOM):
#   web/walkthrough/rules.json
#   web/walkthrough/questions.json
#   web/walkthrough/scenarios.json
#   web/walkthrough/data.js     (window.NASFAA_DATA bundle, incl. build SHA)

require 'yaml'
require 'json'
require 'time'
require 'shellwords'

ROOT = File.expand_path('../..', __dir__)
OUT  = File.expand_path(__dir__)

SOURCES = {
  'rules.json'     => 'nasfaa_rules.yml',
  'questions.json' => 'nasfaa_questions.yml',
  'scenarios.json' => 'nasfaa_scenarios.yml'
}.freeze

def load_yaml(src_name)
  YAML.safe_load_file(File.join(ROOT, src_name))
end

def write_file(out_name, body)
  out_path = File.join(OUT, out_name)
  File.open(out_path, 'w:UTF-8') do |f|
    f.write(body)
    f.write("\n") unless body.end_with?("\n")
  end
  puts "wrote #{out_name} (#{File.size(out_path)} bytes)"
end

def git_sha
  sha = `git -C #{ROOT.shellescape} rev-parse HEAD 2>/dev/null`.strip
  sha.empty? ? 'dev' : sha
rescue StandardError
  'dev'
end

bundle = {}
SOURCES.each do |out_name, src_name|
  data = load_yaml(src_name)
  bundle[out_name.sub('.json', '')] = data
  write_file(out_name, JSON.pretty_generate(data))
end

bundle['build'] = { 'sha' => git_sha, 'generated_at' => Time.now.utc.iso8601 }

data_js = +"// data.js — generated by build.rb from the canonical YAML.\n"
data_js << "// Re-run `ruby web/walkthrough/build.rb` after editing YAML.\n"
data_js << "window.NASFAA_DATA = #{JSON.pretty_generate(bundle)};\n"
write_file('data.js', data_js)
puts 'done.'
