// data.js — generated by build.rb from the canonical YAML.
// Re-run `ruby web/walkthrough/build.rb` after editing YAML.
window.NASFAA_DATA = {
  "rules": {
    "metadata": {
      "version": "1.0",
      "description": "NASFAA Data Sharing Decision Tree Rules",
      "evaluation_order": "first_match_wins",
      "input_type": "boolean"
    },
    "validation": {
      "required_inputs": [
        "includes_fti"
      ],
      "mutually_exclusive_groups": [
        [
          "includes_fti",
          "!includes_fti"
        ]
      ]
    },
    "result_types": {
      "permit": "Disclosure is permitted",
      "deny": "Disclosure is not permitted",
      "permit_with_caution": "Disclosure permitted with caution",
      "permit_with_scope": "Disclosure permitted with scope limitations"
    },
    "inputs": {
      "includes_fti": "boolean",
      "disclosure_to_student": "boolean",
      "disclosure_to_contributor_parent_or_spouse": "boolean",
      "is_fafsa_data": "boolean",
      "used_for_aid_admin": "boolean",
      "disclosure_to_scholarship_org": "boolean",
      "explicit_written_consent": "boolean",
      "research_promote_attendance": "boolean",
      "hea_written_consent": "boolean",
      "ferpa_written_consent": "boolean",
      "directory_info_and_not_opted_out": "boolean",
      "to_school_official_legitimate_interest": "boolean",
      "due_to_judicial_order_or_subpoena_or_financial_aid": "boolean",
      "to_other_school_enrollment_transfer": "boolean",
      "to_authorized_representatives": "boolean",
      "to_research_org_ferpa": "boolean",
      "to_accrediting_agency": "boolean",
      "parent_of_dependent_student": "boolean",
      "otherwise_permitted_under_99_31": "boolean",
      "contains_pii": "boolean"
    },
    "results": null,
    "rules": [
      {
        "id": "FTI_R1_student",
        "when_all": [
          "includes_fti",
          "disclosure_to_student"
        ],
        "result": "permit"
      },
      {
        "id": "FTI_R2_aid_admin_school_official",
        "when_all": [
          "includes_fti",
          "used_for_aid_admin",
          "to_school_official_legitimate_interest"
        ],
        "result": "permit"
      },
      {
        "id": "FTI_R2b_aid_admin_deny",
        "when_all": [
          "includes_fti",
          "used_for_aid_admin"
        ],
        "result": "deny"
      },
      {
        "id": "FTI_R3_scholarship_with_consent",
        "when_all": [
          "includes_fti",
          "disclosure_to_scholarship_org",
          "explicit_written_consent"
        ],
        "result": "permit"
      },
      {
        "id": "FTI_DENY_default",
        "when_all": [
          "includes_fti"
        ],
        "result": "deny"
      },
      {
        "id": "FAFSA_R1_to_student",
        "when_all": [
          "!includes_fti",
          "disclosure_to_student"
        ],
        "result": "permit"
      },
      {
        "id": "FAFSA_R4_scholarship_with_consent",
        "when_all": [
          "!includes_fti",
          "is_fafsa_data",
          "!used_for_aid_admin",
          "disclosure_to_scholarship_org",
          "explicit_written_consent"
        ],
        "result": "permit"
      },
      {
        "id": "FAFSA_R6_HEA_written_consent",
        "when_all": [
          "!includes_fti",
          "is_fafsa_data",
          "!used_for_aid_admin",
          "!research_promote_attendance",
          "hea_written_consent"
        ],
        "result": "permit"
      },
      {
        "id": "FAFSA_R6b_no_hea_consent_review_deny",
        "when_all": [
          "!includes_fti",
          "is_fafsa_data",
          "!disclosure_to_contributor_parent_or_spouse",
          "!used_for_aid_admin",
          "!research_promote_attendance",
          "!hea_written_consent"
        ],
        "result": "deny",
        "caution_note": "Review §99.31(a)(9)(ii) and consult legal counsel if subpoena, court order, or other law enforcement request."
      },
      {
        "id": "FAFSA_R7_no_pii",
        "when_all": [
          "!includes_fti",
          "is_fafsa_data",
          "!used_for_aid_admin",
          "!contains_pii"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R0_written_consent",
        "when_all": [
          "!includes_fti",
          "ferpa_written_consent"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R1_directory_info",
        "when_all": [
          "!includes_fti",
          "directory_info_and_not_opted_out"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R2_school_official_LEI",
        "when_all": [
          "!includes_fti",
          "to_school_official_legitimate_interest"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R3_judicial_or_finaid_related",
        "when_all": [
          "!includes_fti",
          "due_to_judicial_order_or_subpoena_or_financial_aid"
        ],
        "result": "permit_with_caution"
      },
      {
        "id": "FERPA_R4_other_school_enrollment",
        "when_all": [
          "!includes_fti",
          "to_other_school_enrollment_transfer"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R5_authorized_representatives",
        "when_all": [
          "!includes_fti",
          "to_authorized_representatives"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R6_research_org_predictive_tests_admin_aid_improve_instruction",
        "when_all": [
          "!includes_fti",
          "to_research_org_ferpa"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R7_accrediting_agency",
        "when_all": [
          "!includes_fti",
          "to_accrediting_agency"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R8_parent_of_dependent_student",
        "when_all": [
          "!includes_fti",
          "parent_of_dependent_student"
        ],
        "result": "permit"
      },
      {
        "id": "FERPA_R9_otherwise_permitted_99_31",
        "when_all": [
          "!includes_fti",
          "otherwise_permitted_under_99_31"
        ],
        "result": "permit"
      },
      {
        "id": "NONFTI_DENY_default",
        "when_all": [
          "!includes_fti"
        ],
        "result": "deny"
      }
    ]
  },
  "questions": {
    "start": "fti_check",
    "nodes": {
      "fti_check": {
        "type": "question",
        "box": "1 (both pages)",
        "text": "Does the disclosure include Federal Tax Information (FTI)?",
        "pdf_text": "Does the disclosure include Federal Tax Information (FTI): Federal tax return information received from the IRS by ED under the FUTURE Act Information Sharing Program? (See pg. 2 for list of FTI data elements)",
        "help": "FTI includes any tax return data obtained through the IRS Data Retrieval Tool or direct data exchange with the IRS.",
        "field": "includes_fti",
        "on_yes": "fti_to_student",
        "on_no": "nonfti_to_student"
      },
      "fti_to_student": {
        "type": "question",
        "box": "1 (Page 2)",
        "text": "Is the disclosure to the student (the data subject)?",
        "pdf_text": "Is the disclosure to the student? 1098h(c)(1)(A)(ii)",
        "field": "disclosure_to_student",
        "on_yes": "result_FTI_R1_student",
        "on_no": "fti_aid_admin"
      },
      "fti_aid_admin": {
        "type": "question",
        "box": "2 (Page 2)",
        "text": "Will the information be used for financial aid administration (application, award, or administration of Title IV aid)?",
        "pdf_text": "Will the information be used for the application, award, or administration of financial aid, per ED's definition? 1090(a)(3)(C)(i)",
        "field": "used_for_aid_admin",
        "on_yes": "fti_school_official",
        "on_no": "fti_scholarship"
      },
      "fti_school_official": {
        "type": "question",
        "box": "4 (Page 2)",
        "text": "Is the recipient a school official with legitimate educational interest (LEI)?",
        "pdf_text": "Is the disclosure to other school officials determined to have a legitimate educational interest in the disclosed information? 99.31(a)(1)",
        "help": "A school official has LEI if they need the information to fulfill their professional responsibilities as designated in the institution's annual FERPA notification.",
        "field": "to_school_official_legitimate_interest",
        "on_yes": "result_FTI_R2_aid_admin_school_official",
        "on_no": "result_FTI_R2b_aid_admin_deny"
      },
      "fti_scholarship": {
        "type": "question",
        "box": "3 (Page 2)",
        "text": "Is the disclosure to a scholarship, tribal, or other assistance organization with the student's explicit written consent?",
        "pdf_text": "Is the disclosure to a scholarship granting organization, tribal organization, or other organization assisting the applicant in applying for and receiving federal, state, local, or tribal financial assistance for any component of the applicant's cost of attendance, and has the student provided explicit written consent? 1098h(b)(1)(B)",
        "fields": [
          "disclosure_to_scholarship_org",
          "explicit_written_consent"
        ],
        "on_yes": "result_FTI_R3_scholarship_with_consent",
        "on_no": "result_FTI_DENY_default"
      },
      "result_FTI_R1_student": {
        "type": "result",
        "result": "permit",
        "rule_id": "FTI_R1_student",
        "message": "The student may always access their own records, including FTI.",
        "citation": "IRC §6103(l)(13)"
      },
      "result_FTI_R2_aid_admin_school_official": {
        "type": "result",
        "result": "permit",
        "rule_id": "FTI_R2_aid_admin_school_official",
        "message": "FTI may be shared with a school official who has legitimate educational interest for aid administration.",
        "citation": "IRC §6103(l)(13)(B); FERPA 34 CFR §99.31(a)(1)"
      },
      "result_FTI_R2b_aid_admin_deny": {
        "type": "result",
        "result": "deny",
        "rule_id": "FTI_R2b_aid_admin_deny",
        "message": "The recipient has not been designated as a school official with legitimate educational interest. FTI may not be released.",
        "citation": "IRC §6103(l)(13)"
      },
      "result_FTI_R3_scholarship_with_consent": {
        "type": "result",
        "result": "permit",
        "rule_id": "FTI_R3_scholarship_with_consent",
        "message": "FTI may be shared with a scholarship organization when the student has provided explicit written consent.",
        "citation": "IRC §6103(l)(13)(D)"
      },
      "result_FTI_DENY_default": {
        "type": "result",
        "result": "deny",
        "rule_id": "FTI_DENY_default",
        "message": "No applicable exception permits the release of Federal Tax Information in this situation.",
        "citation": "IRC §6103"
      },
      "nonfti_to_student": {
        "type": "question",
        "box": "2 (Page 1)",
        "text": "Is the disclosure to the student (the data subject)?",
        "pdf_text": "Is the disclosure to the student?",
        "field": "disclosure_to_student",
        "on_yes": "result_FAFSA_R1_to_student",
        "on_no": "nonfti_fafsa_check"
      },
      "nonfti_fafsa_check": {
        "type": "question",
        "box": "3 (Page 1)",
        "text": "Is the data FAFSA data (as defined by the Department of Education)?",
        "pdf_text": "Is the information being requested considered FAFSA data per ED's definitions? (See pg. 2 for list of what is considered FAFSA data)",
        "help": "FAFSA data includes information collected on or derived from the Free Application for Federal Student Aid.",
        "field": "is_fafsa_data",
        "on_yes": "fafsa_contributor",
        "on_no": "ferpa_consent"
      },
      "fafsa_contributor": {
        "type": "question",
        "box": "4 (Page 1)",
        "text": "Is the disclosure to a parent or spouse who is a FAFSA contributor?",
        "pdf_text": "Is the disclosure to the parent or spouse who contributed to the FAFSA?*",
        "help": "Under the FAFSA Simplification Act, a 'contributor' is someone who provided financial information on the student's FAFSA.",
        "field": "disclosure_to_contributor_parent_or_spouse",
        "on_yes": "ferpa_consent",
        "on_no": "fafsa_aid_admin"
      },
      "fafsa_aid_admin": {
        "type": "question",
        "box": "5 (Page 1)",
        "text": "Will the data be used for financial aid administration?",
        "pdf_text": "Will the information be used for the application, award, and/or administration of financial aid, per ED's definition?",
        "help": "Aid admin alone does not authorize disclosure — the recipient must also be a school official with legitimate educational interest (Box 12) or another §99.31 exception must apply.",
        "field": "used_for_aid_admin",
        "on_yes": "ferpa_school_official",
        "on_no": "fafsa_scholarship"
      },
      "fafsa_scholarship": {
        "type": "question",
        "box": "6 (Page 1)",
        "text": "Is the disclosure to a scholarship, tribal, or other assistance organization with the student's explicit written consent?",
        "pdf_text": "Is the disclosure to a scholarship granting organization, tribal organization, or other organization assisting the applicant in applying for and receiving federal, state, local, or tribal financial assistance for any component of the applicant's cost of attendance, and has the student provided explicit written consent? §1090(a)(3)(B)",
        "fields": [
          "disclosure_to_scholarship_org",
          "explicit_written_consent"
        ],
        "on_yes": "result_FAFSA_R4_scholarship_with_consent",
        "on_no": "fafsa_research"
      },
      "fafsa_research": {
        "type": "question",
        "box": "7 (Page 1)",
        "text": "Is the data being used for institutional research promoting college attendance, persistence, or completion?",
        "pdf_text": "Is the disclosure for research by or on behalf of the institution to promote college attendance, persistence, and completion? §1090(a)(3)(C)",
        "field": "research_promote_attendance",
        "on_yes": "fafsa_pii",
        "on_no": "fafsa_hea_consent"
      },
      "fafsa_hea_consent": {
        "type": "question",
        "box": "8 (Page 1)",
        "text": "Has the student provided HEA written consent under §1090(a)(3)(C)?",
        "pdf_text": "Has the student provided written consent for disclosure under the Higher Education Act (HEA)? §1090(a)(3)(C)",
        "help": "This is the general Higher Education Act consent for FAFSA data disclosure, broader than FERPA consent.",
        "field": "hea_written_consent",
        "on_yes": "result_FAFSA_R6_HEA_written_consent",
        "on_no": "result_FAFSA_R6b_no_hea_consent_review_deny"
      },
      "fafsa_pii": {
        "type": "question",
        "box": "9 (Page 1)",
        "text": "Does the data contain personally identifiable information (PII)?",
        "pdf_text": "Does the disclosure contain personally identifiable information (PII)?",
        "field": "contains_pii",
        "on_yes": "ferpa_consent",
        "on_no": "result_FAFSA_R7_no_pii"
      },
      "ferpa_consent": {
        "type": "question",
        "box": "10",
        "text": "Has the student provided FERPA written consent for this disclosure?",
        "pdf_text": "Has the student provided written consent for disclosure under the Family Educational Rights and Privacy Act (FERPA)? 99.30",
        "help": "FERPA written consent must specify the records to be disclosed, the purpose, and the party to whom disclosure may be made.",
        "field": "ferpa_written_consent",
        "on_yes": "result_FERPA_R0_written_consent",
        "on_no": "ferpa_directory"
      },
      "ferpa_directory": {
        "type": "question",
        "box": "11",
        "text": "Is the data directory information and the student has not opted out?",
        "pdf_text": "Is the information being requested as directory information and has the student not opted out? 99.31(a)(11)",
        "help": "Directory information (name, address, dates of attendance, degree, etc.) may be disclosed if designated in the institution's FERPA notice and the student has not restricted it.",
        "field": "directory_info_and_not_opted_out",
        "on_yes": "result_FERPA_R1_directory_info",
        "on_no": "ferpa_school_official"
      },
      "ferpa_school_official": {
        "type": "question",
        "box": "12",
        "text": "Is the recipient a school official with legitimate educational interest?",
        "pdf_text": "Is the disclosure to other school officials determined to have a legitimate educational interest in the disclosed information? 99.31(a)(1)",
        "field": "to_school_official_legitimate_interest",
        "on_yes": "result_FERPA_R2_school_official_LEI",
        "on_no": "ferpa_judicial"
      },
      "ferpa_judicial": {
        "type": "question",
        "box": "13",
        "text": "Is the disclosure due to a lawfully issued judicial order, subpoena, or related to financial aid?",
        "pdf_text": "Is the information being requested as a result of a judicial order or subpoena, 99.31(a)(9), or in relation to financial aid for which the student has applied or received under 99.31(a)(4)(i)?",
        "field": "due_to_judicial_order_or_subpoena_or_financial_aid",
        "on_yes": "result_FERPA_R3_judicial_or_finaid_related",
        "on_no": "ferpa_transfer"
      },
      "ferpa_transfer": {
        "type": "question",
        "box": "14",
        "text": "Is the disclosure to officials at another school where the student seeks or intends to enroll?",
        "pdf_text": "Is the disclosure to officials of another school where the student seeks or intends to enroll, or where the student is already enrolled for purposes related to the student's enrollment or transfer? 99.31(a)(2)",
        "field": "to_other_school_enrollment_transfer",
        "on_yes": "result_FERPA_R4_other_school_enrollment",
        "on_no": "ferpa_authorized_rep"
      },
      "ferpa_authorized_rep": {
        "type": "question",
        "box": "15",
        "text": "Is the disclosure to authorized representatives (Comptroller General, Attorney General, Secretary of Education, or state/local educational authorities)?",
        "pdf_text": "Is the disclosure to authorized representatives of the Comptroller General of the United States, The Attorney General of the United States, the Secretary, or state and local educational authorities? 99.31(a)(3)",
        "field": "to_authorized_representatives",
        "on_yes": "result_FERPA_R5_authorized_representatives",
        "on_no": "ferpa_research_org"
      },
      "ferpa_research_org": {
        "type": "question",
        "box": "16",
        "text": "Is the disclosure to a research organization for developing predictive tests, administering student aid, or improving instruction?",
        "pdf_text": "Is the disclosure to an organization conducting research for, or on behalf of, your institution to: (A) Develop, validate, or administer predictive tests; (B) Administer student aid programs; or (C) Improve instruction? 99.31(a)(6)",
        "field": "to_research_org_ferpa",
        "on_yes": "result_FERPA_R6_research_org_predictive_tests_admin_aid_improve_instruction",
        "on_no": "ferpa_accreditor"
      },
      "ferpa_accreditor": {
        "type": "question",
        "box": "17",
        "text": "Is the disclosure to an accrediting organization to carry out its accrediting functions?",
        "pdf_text": "Is the disclosure to an accrediting agency to carry out their accrediting functions? 99.31(a)(7)",
        "field": "to_accrediting_agency",
        "on_yes": "result_FERPA_R7_accrediting_agency",
        "on_no": "ferpa_parent"
      },
      "ferpa_parent": {
        "type": "question",
        "box": "18",
        "text": "Is the disclosure to the parent of a student who is a dependent for IRS tax purposes?",
        "pdf_text": "Is the disclosure to the parent of a dependent student, as defined in section 152 of the Internal Revenue Code of 1986? 99.31(a)(8)",
        "help": "This uses the IRS definition of dependency (claimed on tax return), not the FAFSA definition.",
        "field": "parent_of_dependent_student",
        "on_yes": "result_FERPA_R8_parent_of_dependent_student",
        "on_no": "ferpa_otherwise"
      },
      "ferpa_otherwise": {
        "type": "question",
        "box": "19",
        "text": "Is the disclosure otherwise permitted under FERPA §99.31 (e.g., health/safety emergency, sex offender registry)?",
        "pdf_text": "Is the disclosure otherwise permitted under 99.31?",
        "field": "otherwise_permitted_under_99_31",
        "on_yes": "result_FERPA_R9_otherwise_permitted_99_31",
        "on_no": "result_NONFTI_DENY_default"
      },
      "result_FAFSA_R1_to_student": {
        "type": "result",
        "result": "permit",
        "rule_id": "FAFSA_R1_to_student",
        "message": "The student has the right to inspect their own education records.",
        "citation": "FERPA 34 CFR §99.10"
      },
      "result_FAFSA_R4_scholarship_with_consent": {
        "type": "result",
        "result": "permit",
        "rule_id": "FAFSA_R4_scholarship_with_consent",
        "message": "FAFSA data may be shared with a scholarship organization when the student has provided explicit written consent.",
        "citation": "HEA §1098h(b)"
      },
      "result_FAFSA_R6_HEA_written_consent": {
        "type": "result",
        "result": "permit",
        "rule_id": "FAFSA_R6_HEA_written_consent",
        "message": "The student has provided HEA written consent for FAFSA data disclosure.",
        "citation": "HEA §1090(a)(3)(C)"
      },
      "result_FAFSA_R6b_no_hea_consent_review_deny": {
        "type": "result",
        "result": "deny",
        "rule_id": "FAFSA_R6b_no_hea_consent_review_deny",
        "message": "Disclosure Not Permitted. Review §99.31(a)(9)(ii) and consult legal counsel if this is a subpoena, court order, or other law enforcement request.",
        "citation": "HEA §1090(a)(3)(C); FERPA 34 CFR §99.31(a)(9)(ii)"
      },
      "result_FAFSA_R7_no_pii": {
        "type": "result",
        "result": "permit",
        "rule_id": "FAFSA_R7_no_pii",
        "message": "The data contains no personally identifiable information — FERPA privacy protections do not apply.",
        "citation": "FERPA does not apply to de-identified/aggregate data"
      },
      "result_FERPA_R0_written_consent": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R0_written_consent",
        "message": "The student has provided valid FERPA written consent.",
        "citation": "FERPA 34 CFR §99.30"
      },
      "result_FERPA_R1_directory_info": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R1_directory_info",
        "message": "The data is directory information and the student has not opted out.",
        "citation": "FERPA 34 CFR §99.31(a)(11); §99.37"
      },
      "result_FERPA_R2_school_official_LEI": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R2_school_official_LEI",
        "message": "The recipient is a school official with legitimate educational interest.",
        "citation": "FERPA 34 CFR §99.31(a)(1)"
      },
      "result_FERPA_R3_judicial_or_finaid_related": {
        "type": "result",
        "result": "permit_with_caution",
        "rule_id": "FERPA_R3_judicial_or_finaid_related",
        "message": "Consult legal counsel regarding notification requirements under §99.31(a)(9)(ii) before responding to the subpoena or order.",
        "citation": "FERPA 34 CFR §99.31(a)(9); §99.31(a)(4)(i)"
      },
      "result_FERPA_R4_other_school_enrollment": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R4_other_school_enrollment",
        "message": "Records may be sent to officials at another school for enrollment or transfer purposes.",
        "citation": "FERPA 34 CFR §99.31(a)(2)"
      },
      "result_FERPA_R5_authorized_representatives": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R5_authorized_representatives",
        "message": "Records may be shared with authorized representatives for audit or evaluation purposes.",
        "citation": "FERPA 34 CFR §99.31(a)(3); §99.35"
      },
      "result_FERPA_R6_research_org_predictive_tests_admin_aid_improve_instruction": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R6_research_org_predictive_tests_admin_aid_improve_instruction",
        "message": "Records may be shared with research organizations under the FERPA research exception.",
        "citation": "FERPA 34 CFR §99.31(a)(6)"
      },
      "result_FERPA_R7_accrediting_agency": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R7_accrediting_agency",
        "message": "Records may be shared with accrediting organizations.",
        "citation": "FERPA 34 CFR §99.31(a)(7)"
      },
      "result_FERPA_R8_parent_of_dependent_student": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R8_parent_of_dependent_student",
        "message": "Records may be shared with parents of IRS-dependent students.",
        "citation": "FERPA 34 CFR §99.31(a)(8)"
      },
      "result_FERPA_R9_otherwise_permitted_99_31": {
        "type": "result",
        "result": "permit",
        "rule_id": "FERPA_R9_otherwise_permitted_99_31",
        "message": "Disclosure is permitted under another FERPA §99.31 exception.",
        "citation": "FERPA 34 CFR §99.31"
      },
      "result_NONFTI_DENY_default": {
        "type": "result",
        "result": "deny",
        "rule_id": "NONFTI_DENY_default",
        "message": "No applicable FERPA exception permits this disclosure. The data may not be released.",
        "citation": "FERPA 34 CFR Part 99"
      }
    }
  },
  "scenarios": {
    "scenarios": [
      {
        "id": "student_views_own_fti",
        "name": "Student Views Own Tax Return Information",
        "description": "A dependent student visits the financial aid office and asks to review the Federal Tax Information (FTI) that was submitted as part of their FAFSA application via the IRS Data Retrieval Tool. Because the student is the data subject, disclosure to the student is always permitted regardless of the data's FTI status.\n",
        "inputs": {
          "includes_fti": true,
          "disclosure_to_student": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FTI_R1_student"
        },
        "citation": "IRC §6103(l)(13); disclosure to the data subject is always permitted",
        "tags": [
          "fti",
          "student",
          "permit",
          "basic"
        ]
      },
      {
        "id": "aid_director_reviews_fti_for_packaging",
        "name": "Aid Director Reviews FTI for Award Packaging",
        "description": "The Director of Financial Aid, who has been designated as a school official with legitimate educational interest (LEI) under FERPA, reviews a student's tax return information to calculate their Expected Family Contribution and prepare a financial aid award package. The aid director's role in administering Title IV aid qualifies as LEI.\n",
        "inputs": {
          "includes_fti": true,
          "used_for_aid_admin": true,
          "to_school_official_legitimate_interest": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FTI_R2_aid_admin_school_official"
        },
        "citation": "IRC §6103(l)(13)(B); FERPA 34 CFR §99.31(a)(1) — school official with LEI",
        "tags": [
          "fti",
          "aid_admin",
          "school_official",
          "permit"
        ]
      },
      {
        "id": "contractor_requests_fti_without_lei",
        "name": "Third-Party Servicer Requests FTI Without LEI Designation",
        "description": "A third-party loan servicer contracted by the university requests access to student FTI data to verify income for repayment plan purposes. Although the servicer works on financial aid administration, they have not been formally designated as a school official with legitimate educational interest in the institution's FERPA policy. Without LEI, the FTI disclosure is denied even though the purpose is aid-related.\n",
        "inputs": {
          "includes_fti": true,
          "used_for_aid_admin": true
        },
        "expected": {
          "result": "deny",
          "rule_id": "FTI_R2b_aid_admin_deny"
        },
        "citation": "IRC §6103(l)(13) — aid administration alone is insufficient without LEI",
        "tags": [
          "fti",
          "aid_admin",
          "deny"
        ]
      },
      {
        "id": "tribal_scholarship_with_consent",
        "name": "Tribal Scholarship Organization With Explicit Written Consent",
        "description": "A tribal scholarship organization requests a student's FTI to verify eligibility for a need-based tribal education grant. The student has signed an explicit written consent form specifically authorizing the release of their tax return information to this organization. Because the disclosure is to a scholarship organization with proper consent (and is NOT routed through the aid administration path), it is permitted.\n",
        "inputs": {
          "includes_fti": true,
          "disclosure_to_scholarship_org": true,
          "explicit_written_consent": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FTI_R3_scholarship_with_consent"
        },
        "citation": "IRC §6103(l)(13)(D) — scholarship/grant organization with explicit consent",
        "tags": [
          "fti",
          "scholarship",
          "consent",
          "permit"
        ]
      },
      {
        "id": "external_auditor_requests_fti",
        "name": "External Auditor Requests FTI for Compliance Review",
        "description": "An external auditing firm conducting a financial compliance review of the university's Title IV programs requests access to student FTI data. The auditor is not a school official, not using the data for direct aid administration, not a scholarship organization, and the students have not consented to this disclosure. No FTI exception applies — the catch-all deny fires.\n",
        "inputs": {
          "includes_fti": true
        },
        "expected": {
          "result": "deny",
          "rule_id": "FTI_DENY_default"
        },
        "citation": "IRC §6103 — FTI is protected by default; no applicable exception",
        "tags": [
          "fti",
          "deny",
          "default"
        ]
      },
      {
        "id": "student_reviews_own_fafsa",
        "name": "Student Reviews Own FAFSA Submission",
        "description": "A first-generation college student visits the financial aid office to review the FAFSA data that was submitted on their behalf. As the data subject, the student has an absolute right to inspect their own education records under FERPA, regardless of whether the data is FAFSA-specific, contains PII, or involves any other conditions. This rule fires before any FAFSA-specific checks.\n",
        "inputs": {
          "disclosure_to_student": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FAFSA_R1_to_student"
        },
        "citation": "FERPA 34 CFR §99.10 — student's right to inspect own education records",
        "tags": [
          "fafsa",
          "student",
          "permit",
          "basic"
        ]
      },
      {
        "id": "aid_office_processes_awards",
        "name": "Aid Office Uses FAFSA Data to Calculate Awards",
        "description": "The financial aid office uses a student's FAFSA data — including Student Aid Index (SAI), dependency status, and household size — to calculate the student's financial need and prepare a Title IV aid package. This is the core use case for FAFSA data. Per the PDF, aid admin (Box 5 Yes) routes through the FERPA school official check (Box 12); since the aid office staff have been designated as school officials with legitimate educational interest, the disclosure is permitted under §99.31(a)(1).\n",
        "inputs": {
          "is_fafsa_data": true,
          "used_for_aid_admin": true,
          "to_school_official_legitimate_interest": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R2_school_official_LEI"
        },
        "citation": "HEA §1090(a); §1098h; FERPA 34 CFR §99.31(a)(1) — aid admin via school official with LEI",
        "tags": [
          "fafsa",
          "aid_admin",
          "school_official",
          "permit"
        ]
      },
      {
        "id": "aid_admin_use_without_lei",
        "name": "Aid Administrator Forwards Data to Non-School-Official (No LEI)",
        "description": "A staff member uses FAFSA data for aid administration (Box 5 Yes) and forwards the data to a third party who has NOT been designated a school official with legitimate educational interest in the institution's FERPA notification. Per the PDF, aid admin alone does not authorize disclosure — Box 5 Yes routes to Box 12 (LEI check), and without LEI or another §99.31 exception the disclosure is denied.\n",
        "inputs": {
          "is_fafsa_data": true,
          "used_for_aid_admin": true
        },
        "expected": {
          "result": "deny",
          "rule_id": "NONFTI_DENY_default"
        },
        "citation": "HEA §1090(a); §1098h — aid admin requires a §99.31 exception (typically LEI) to authorize disclosure",
        "tags": [
          "fafsa",
          "aid_admin",
          "deny"
        ]
      },
      {
        "id": "scholarship_foundation_with_student_consent",
        "name": "Scholarship Foundation Requests FAFSA Data With Student Consent",
        "description": "A private scholarship foundation that awards need-based grants requests FAFSA data to evaluate a student's eligibility. The student has signed an explicit written consent form authorizing the aid office to share their FAFSA information with this specific foundation. The combination of the scholarship purpose and explicit consent authorizes disclosure.\n",
        "inputs": {
          "is_fafsa_data": true,
          "disclosure_to_scholarship_org": true,
          "explicit_written_consent": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FAFSA_R4_scholarship_with_consent"
        },
        "citation": "HEA §1098h(b) — scholarship organization with explicit written consent",
        "tags": [
          "fafsa",
          "scholarship",
          "consent",
          "permit"
        ]
      },
      {
        "id": "institutional_researcher_studies_persistence",
        "name": "Institutional Researcher Studies Student Persistence (De-identified)",
        "description": "The university's Office of Institutional Research uses FAFSA data to study factors affecting student persistence, retention, and degree completion rates. The research aims to identify at-risk populations and improve institutional support programs. Per the PDF, research promoting college attendance (Box 7 Yes) still requires passing the PII gate (Box 9). Since the data has been de-identified (no PII), disclosure is permitted.\n",
        "inputs": {
          "is_fafsa_data": true,
          "research_promote_attendance": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FAFSA_R7_no_pii"
        },
        "citation": "FERPA does not apply to de-identified/aggregate data",
        "tags": [
          "fafsa",
          "research",
          "permit"
        ]
      },
      {
        "id": "state_grant_agency_with_hea_consent",
        "name": "State Grant Agency Receives FAFSA Data Under HEA Consent",
        "description": "A state higher education agency that administers state financial aid programs receives FAFSA data for students who have provided the general HEA written consent under §1090(a)(3)(C). This consent, which is broader than FERPA consent, authorizes sharing FAFSA data with state agencies and other authorized entities for financial aid purposes.\n",
        "inputs": {
          "is_fafsa_data": true,
          "hea_written_consent": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FAFSA_R6_HEA_written_consent"
        },
        "citation": "HEA §1090(a)(3)(C) — general HEA consent for FAFSA data disclosure",
        "tags": [
          "fafsa",
          "consent",
          "state_agency",
          "permit"
        ]
      },
      {
        "id": "deidentified_fafsa_aggregate_report",
        "name": "De-Identified FAFSA Aggregate Statistics Report",
        "description": "Institutional Research prepares an aggregate retention/persistence analysis using FAFSA-derived data to inform student-success programming (Box 7 Yes — research promoting attendance/completion). All personally identifiable information has been stripped before analysis, so the Box 9 PII gate evaluates \"No\" and the disclosure is permitted without requiring FERPA consent or another §99.31 exception.\n",
        "inputs": {
          "is_fafsa_data": true,
          "research_promote_attendance": true,
          "contains_pii": false
        },
        "expected": {
          "result": "permit",
          "rule_id": "FAFSA_R7_no_pii"
        },
        "citation": "FERPA does not apply to de-identified/aggregate data without PII",
        "tags": [
          "fafsa",
          "no_pii",
          "research",
          "permit"
        ]
      },
      {
        "id": "outside_inquiry_no_hea_consent",
        "name": "Outside Inquiry for FAFSA Data Without HEA Consent (Box 8 No)",
        "description": "A third party (e.g., a private organization, journalist, or unrelated government office) requests FAFSA data on a specific applicant. The request is not for aid administration, not from a scholarship organization with explicit consent, not for institutional research promoting attendance, and the student has not provided HEA §1090(a)(3)(C) written consent. Under the PDF's Box 8 No gray terminal, the disclosure is not permitted — FAFSA data without HEA consent cannot be rescued by FERPA exceptions on this path. Review §99.31(a)(9)(ii) if the request is a subpoena, court order, or law enforcement demand.\n",
        "inputs": {
          "is_fafsa_data": true,
          "contains_pii": true
        },
        "expected": {
          "result": "deny",
          "rule_id": "FAFSA_R6b_no_hea_consent_review_deny"
        },
        "citation": "HEA §1090(a)(3)(C); FERPA 34 CFR §99.31(a)(9)(ii)",
        "tags": [
          "fafsa",
          "hea",
          "deny"
        ]
      },
      {
        "id": "student_signs_ferpa_release_for_employer",
        "name": "Student Signs FERPA Release for Potential Employer",
        "description": "A graduating senior signs a FERPA consent form authorizing the financial aid office to release their education records (including GPA, enrollment status, and financial aid history) to a potential employer conducting a background check. With valid FERPA written consent, the disclosure is permitted regardless of the data type or recipient.\n",
        "inputs": {
          "ferpa_written_consent": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R0_written_consent"
        },
        "citation": "FERPA 34 CFR §99.30 — disclosure with prior written consent of the student",
        "tags": [
          "ferpa",
          "consent",
          "permit"
        ]
      },
      {
        "id": "alumni_association_receives_directory_info",
        "name": "Alumni Association Receives Directory Information",
        "description": "The university's alumni association requests names, graduation dates, and degree programs for the graduating class to send congratulatory materials and membership invitations. This information has been designated as \"directory information\" under the institution's FERPA policy, and none of the affected students have opted out of directory information disclosure.\n",
        "inputs": {
          "directory_info_and_not_opted_out": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R1_directory_info"
        },
        "citation": "FERPA 34 CFR §99.31(a)(11); §99.37 — directory information disclosure",
        "tags": [
          "ferpa",
          "directory_info",
          "permit"
        ]
      },
      {
        "id": "academic_advisor_reviews_student_record",
        "name": "Academic Advisor Reviews Student Education Record",
        "description": "An academic advisor accesses a student's education records — including financial aid status, enrollment history, and academic standing — to provide informed advising during course registration. The advisor has been designated as a school official with a legitimate educational interest (LEI) in the institution's annual FERPA notification, and needs the information to perform their professional responsibilities.\n",
        "inputs": {
          "to_school_official_legitimate_interest": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R2_school_official_LEI"
        },
        "citation": "FERPA 34 CFR §99.31(a)(1) — school official with legitimate educational interest",
        "tags": [
          "ferpa",
          "school_official",
          "permit"
        ]
      },
      {
        "id": "court_subpoena_for_student_records",
        "name": "Court Issues Subpoena for Student Financial Aid Records",
        "description": "A court issues a lawfully issued subpoena requiring the university to produce a student's financial aid records as part of a civil proceeding. While the subpoena compels disclosure under FERPA §99.31(a)(9), the institution should consult legal counsel before responding to ensure compliance with the specific notification and procedural requirements of §99.31(a)(9)(ii), which may require reasonable effort to notify the student before disclosure.\n",
        "inputs": {
          "due_to_judicial_order_or_subpoena_or_financial_aid": true
        },
        "expected": {
          "result": "permit_with_caution",
          "rule_id": "FERPA_R3_judicial_or_finaid_related"
        },
        "citation": "FERPA 34 CFR §99.31(a)(9); §99.31(a)(4)(i) — judicial order or subpoena",
        "tags": [
          "ferpa",
          "judicial",
          "subpoena",
          "permit_with_caution",
          "caution"
        ]
      },
      {
        "id": "transfer_records_to_new_institution",
        "name": "Transfer Student Records to Receiving Institution",
        "description": "A student has been accepted for transfer to another university. The current institution's registrar and financial aid office send the student's education records — including transcripts, enrollment history, and financial aid data — to the receiving institution to facilitate the transfer. FERPA permits this disclosure for purposes related to the student's enrollment or transfer.\n",
        "inputs": {
          "to_other_school_enrollment_transfer": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R4_other_school_enrollment"
        },
        "citation": "FERPA 34 CFR §99.31(a)(2) — disclosure to officials at another school for enrollment/transfer",
        "tags": [
          "ferpa",
          "transfer",
          "enrollment",
          "permit"
        ]
      },
      {
        "id": "state_auditor_reviews_aid_compliance",
        "name": "State Auditor Reviews Financial Aid Compliance",
        "description": "A state auditor, acting as an authorized representative of the state educational authority, conducts a compliance review of the university's administration of state financial aid programs. The auditor requires access to individual student records to verify that aid was correctly calculated and disbursed according to state regulations. This falls under the FERPA exception for authorized representatives.\n",
        "inputs": {
          "to_authorized_representatives": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R5_authorized_representatives"
        },
        "citation": "FERPA 34 CFR §99.31(a)(3); §99.35 — authorized representatives for audit/evaluation",
        "tags": [
          "ferpa",
          "authorized_rep",
          "audit",
          "permit"
        ]
      },
      {
        "id": "research_org_studies_aid_effectiveness",
        "name": "Research Organization Studies Financial Aid Effectiveness",
        "description": "An external education research organization has entered into a written agreement with the university to study the effectiveness of different financial aid packaging strategies on student outcomes. The study uses individual-level data to build predictive models for student success. Under FERPA's research exception, organizations may access education records for studies to develop predictive tests, administer student aid programs, or improve instruction.\n",
        "inputs": {
          "to_research_org_ferpa": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R6_research_org_predictive_tests_admin_aid_improve_instruction"
        },
        "citation": "FERPA 34 CFR §99.31(a)(6) — research to develop predictive tests, administer aid, improve instruction",
        "tags": [
          "ferpa",
          "research",
          "permit"
        ]
      },
      {
        "id": "accreditor_reviews_enrollment_data",
        "name": "Accrediting Agency Reviews Enrollment and Outcomes Data",
        "description": "The institution's regional accrediting body (e.g., HLC, SACSCOC) requests enrollment counts, graduation rates, and student outcome data as part of a scheduled accreditation review. The data includes individual student records needed to verify the institution's reported metrics. FERPA permits disclosure to accrediting organizations to carry out their accrediting functions.\n",
        "inputs": {
          "to_accrediting_agency": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R7_accrediting_agency"
        },
        "citation": "FERPA 34 CFR §99.31(a)(7) — accrediting organizations",
        "tags": [
          "ferpa",
          "accrediting",
          "permit"
        ]
      },
      {
        "id": "parent_of_dependent_requests_grades",
        "name": "Parent of IRS-Dependent Student Requests Grades",
        "description": "A parent contacts the university to request their child's grades and financial aid information. The student has been claimed as a dependent on the parent's most recent federal income tax return, satisfying FERPA's dependency test under §99.31(a)(8). Note: this is the IRS dependency definition, not the FAFSA dependency definition — a student can be FAFSA-independent but IRS-dependent, and vice versa.\n",
        "inputs": {
          "parent_of_dependent_student": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R8_parent_of_dependent_student"
        },
        "citation": "FERPA 34 CFR §99.31(a)(8) — parents of dependent students (IRS definition)",
        "tags": [
          "ferpa",
          "parent",
          "dependent",
          "permit"
        ]
      },
      {
        "id": "health_safety_emergency_disclosure",
        "name": "Health and Safety Emergency Disclosure",
        "description": "A student collapses during a campus event and is transported to the emergency room. The Dean of Students office discloses the student's emergency contact information and relevant health records to the hospital under the health/safety emergency exception. This is one of several circumstances covered by the FERPA §99.31 catch-all provision, which encompasses emergencies, sex offender registries, and other specific situations enumerated in the regulation.\n",
        "inputs": {
          "otherwise_permitted_under_99_31": true
        },
        "expected": {
          "result": "permit",
          "rule_id": "FERPA_R9_otherwise_permitted_99_31"
        },
        "citation": "FERPA 34 CFR §99.31(a)(10) — health/safety emergency; §99.36",
        "tags": [
          "ferpa",
          "emergency",
          "otherwise_permitted",
          "permit"
        ]
      },
      {
        "id": "employer_calls_about_student_aid",
        "name": "Employer Inquires About Student's Financial Aid Status",
        "description": "An employer calls the financial aid office asking whether a student employee received financial aid and how much. The employer has no written consent from the student, no subpoena, and no other legal basis for the request. The student's financial aid records are protected education records under FERPA, and none of the §99.31 exceptions apply. The disclosure must be denied.\n",
        "inputs": {},
        "expected": {
          "result": "deny",
          "rule_id": "NONFTI_DENY_default"
        },
        "citation": "FERPA 34 CFR Part 99 — no applicable exception; disclosure prohibited",
        "tags": [
          "ferpa",
          "deny",
          "default",
          "no_basis"
        ]
      }
    ]
  },
  "build": {
    "sha": "88ebeca44cbbf8f0d1df2c9e5cbf41473f0316bc",
    "generated_at": "2026-05-23T11:58:44Z"
  }
};
