#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates web/index.data.js — the build-SHA bundle for the top-level
# landing page (web/index.html) footer.  Mirrors the build-SHA mechanism
# in web/walkthrough/build.rb and web/quiz/build.js so the index footer
# shows the same "Build: <sha>" info as the other pages.
#
#   ruby web/build-index.rb        (or: make build)
#
# Output (gitignored, regenerated each build):
#   web/index.data.js   (window.NASFAA_INDEX = { build: { sha, ... } })

require 'json'
require 'time'
require 'shellwords'

ROOT = File.expand_path('..', __dir__) # repo root (web/ is __dir__)
OUT  = File.expand_path(__dir__)       # web/

def git_sha
  sha = `git -C #{ROOT.shellescape} rev-parse HEAD 2>/dev/null`.strip
  sha.empty? ? 'dev' : sha
rescue StandardError
  'dev'
end

bundle = { 'build' => { 'sha' => git_sha, 'generated_at' => Time.now.utc.iso8601 } }

out_path = File.join(OUT, 'index.data.js')
File.open(out_path, 'w:UTF-8') do |f|
  f.write("// index.data.js — generated by web/build-index.rb.\n")
  f.write("// Re-run `ruby web/build-index.rb` (or `make build`) to refresh.\n")
  f.write("window.NASFAA_INDEX = #{JSON.pretty_generate(bundle)};\n")
end
puts "wrote index.data.js (#{File.size(out_path)} bytes)"
